(() => {
"use strict";
const KEY="shirmani_social_mvp_v2";
const API_KEY="shirmani_social_api_base_v1";
const SESSION_KEY="shirmani_social_session_v1";
const QUESTIONS=["इस क्षण मैं वास्तव में क्या अनुभव कर रहा/रही हूँ?","मेरे उत्तर के पीछे सबसे सरल कारण क्या है?","यदि मैं अपने उत्तर को फिर सुनूँ, तो उसमें क्या स्पष्ट दिखाई देता है?","मेरी बात और किसी दूसरे व्यक्ति की बात में क्या समानता/अंतर है?","आज की मेरी समझ में कौन-सा प्रश्न अभी खुला हुआ है?"];
const defaults={profile:{name:"",bio:"",language:"हिंदी"},posts:[],interviews:[],questionIndex:0};
const clone=()=>JSON.parse(JSON.stringify(defaults));
const load=()=>{try{return Object.assign(clone(),JSON.parse(localStorage.getItem(KEY)||"{}"))}catch{return clone()}};
let state=load();
const apiBase=()=>{try{return (localStorage.getItem(API_KEY)||"").replace(/\/$/,"")}catch{return ""}};
const session=()=>{try{return JSON.parse(sessionStorage.getItem(SESSION_KEY)||"null")}catch{return null}};
const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));renderAll()};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fmt=t=>new Date(t).toLocaleString();
const $=id=>document.getElementById(id);
function status(msg){$("status").textContent=msg;setTimeout(()=>{if($("status").textContent===msg)$("status").textContent=""},2600)}
function authStatus(msg){$("authStatus").textContent=msg}
function apiStatus(msg){$("apiStatus").textContent=msg}
async function api(path,options={}){const base=apiBase();if(!base)throw Error("API_NOT_CONFIGURED");const headers={"Content-Type":"application/json",...(options.headers||{})};const s=session();if(s?.token)headers.Authorization="Bearer "+s.token;const res=await fetch(base+path,{...options,headers});let data={};try{data=await res.json()}catch{}if(!res.ok)throw Error(data.error||("HTTP_"+res.status));return data}
function renderFeed(){const feed=$("feed");if(!state.posts.length){feed.innerHTML='<p class="small">अभी कोई post नहीं है। Create से पहली बात साझा करें।</p>';return}feed.innerHTML=state.posts.slice().reverse().map(p=>'<article class="post"><div class="meta">'+esc(p.authorName||state.profile.name||"आप")+' · '+esc(p.type)+' · '+esc(fmt(p.createdAt))+(p.source==="online"?' · 🌐 online':' · 💾 local')+'</div><p>'+esc(p.text).replace(/\n/g,"<br>")+'</p></article>').join("")}
function renderProfile(){$("displayName").value=state.profile.name||"";$("bio").value=state.profile.bio||"";$("language").value=state.profile.language||"हिंदी"}
function renderInterviews(){$("question").textContent=QUESTIONS[state.questionIndex%QUESTIONS.length];const h=$("interviewHistory");h.innerHTML=state.interviews.length?'<h3>पिछले उत्तर</h3>'+state.interviews.slice().reverse().map(x=>'<div class="result"><div class="meta">'+esc(fmt(x.createdAt))+(x.source==="online"?' · 🌐 online':' · 💾 local')+'</div><div>'+esc(x.question)+'</div><p>'+esc(x.answer).replace(/\n/g,"<br>")+'</p></div>').join(""):'<p class="small">अभी कोई उत्तर सहेजा नहीं गया।</p>'}
function renderSummary(){$("dataSummary").textContent="Profile: "+(state.profile.name||"—")+" · Posts: "+state.posts.length+" · Interviews: "+state.interviews.length+" · API: "+(apiBase()?"configured":"local-only")}
function renderAuth(){$("authStatus").textContent=session()?("Online login: "+(session().account?.email||"authenticated")):"Online login: नहीं";$("apiBase").value=apiBase()}
function renderAll(){renderFeed();renderProfile();renderInterviews();renderSummary();renderAuth()}
function showTab(id){document.querySelectorAll(".panel").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x.dataset.tab===id));location.hash=id}
async function syncFeed(){if(!apiBase())return;try{const data=await api("/v1/feed");state.posts=data.items.map(p=>({id:p.id,text:p.text,type:p.type,createdAt:p.created_at,authorName:p.display_name,source:"online"}));save();status("Online feed ताज़ा हो गया।")}catch(e){apiStatus("Feed sync: "+e.message)}}
document.querySelectorAll("[data-tab]").forEach(b=>b.addEventListener("click",()=>showTab(b.dataset.tab)));
$("postForm").addEventListener("submit",async e=>{e.preventDefault();const text=$("postText").value.trim();if(!text)return;const type=$("postType").value;try{if(session()&&apiBase()){const p=await api("/v1/posts",{method:"POST",body:JSON.stringify({text,type})});state.posts.push({id:p.id,text:p.text,type:p.type,createdAt:p.created_at,authorName:state.profile.name||"आप",source:"online"});status("Post online feed में प्रकाशित हो गया।")}else{state.posts.push({id:crypto.randomUUID(),text,type,createdAt:new Date().toISOString(),source:"local"});status("Post local feed में प्रकाशित हो गया।")}}catch(e){state.posts.push({id:crypto.randomUUID(),text,type,createdAt:new Date().toISOString(),source:"local"});status("Online publish नहीं हुआ; post local में सुरक्षित है।")}$("postText").value="";save();showTab("home")});
$("clearDraft").addEventListener("click",()=>{$("postText").value="";status("Draft साफ़ किया गया।")});
$("profileForm").addEventListener("submit",e=>{e.preventDefault();state.profile={name:$("displayName").value.trim(),bio:$("bio").value.trim(),language:$("language").value};save();status("Profile local device पर सहेजा गया।")});
$("nextQuestion").addEventListener("click",()=>{state.questionIndex=(state.questionIndex+1)%QUESTIONS.length;save()});
$("saveInterview").addEventListener("click",async()=>{const answer=$("answer").value.trim();if(!answer){status("पहले अपना उत्तर लिखें।");return}const q=QUESTIONS[state.questionIndex%QUESTIONS.length];try{if(session()&&apiBase()){const x=await api("/v1/self-interviews",{method:"POST",body:JSON.stringify({question:q,answer})});state.interviews.push({id:x.id,question:x.question,answer:x.answer,createdAt:x.created_at,source:"online"});status("Self-interview उत्तर online सहेजा गया।")}else{state.interviews.push({id:crypto.randomUUID(),question:q,answer,createdAt:new Date().toISOString(),source:"local"});status("Self-interview उत्तर local में सहेजा गया।")}}catch{state.interviews.push({id:crypto.randomUUID(),question:q,answer,createdAt:new Date().toISOString(),source:"local"});status("Online save नहीं हुआ; उत्तर local में सुरक्षित है।")}$("answer").value="";save()});
$("exportData").addEventListener("click",()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="shirmani-social-data.json";a.click();URL.revokeObjectURL(a.href);status("JSON export तैयार है।")});
$("deleteData").addEventListener("click",()=>{if(!confirm("इस browser का पूरा local MVP data मिटाएँ?"))return;localStorage.removeItem(KEY);state=load();renderAll();status("Local data मिटा दिया गया।")});
$("seedDemo").addEventListener("click",()=>{state.posts.push({id:crypto.randomUUID(),text:"यह केवल local demo है — यहाँ कोई वास्तविक follower, view, payment या व्यक्ति का दावा नहीं किया गया है।",type:"Demo",createdAt:new Date().toISOString(),source:"local"});save();status("Demo post जोड़ा गया।")});
$("saveApi").addEventListener("click",()=>{const value=$("apiBase").value.trim().replace(/\/$/,"");if(value&&location.protocol==="https:"&&!value.startsWith("https://")){apiStatus("HTTPS page से केवल HTTPS API इस्तेमाल करें।");return}if(value)localStorage.setItem(API_KEY,value);else localStorage.removeItem(API_KEY);renderAll();apiStatus(value?"API URL सहेजा गया।":"Local-only mode सक्रिय है।")});
$("checkApi").addEventListener("click",async()=>{try{const h=await api("/health");apiStatus("Health: "+h.status+" · DB: "+h.database+" · Auth: "+h.auth);if(session())await syncFeed()}catch(e){apiStatus("API health जाँच असफल: "+e.message)}});
$("authForm").addEventListener("submit",async e=>{e.preventDefault();try{const data=await api("/v1/auth/login",{method:"POST",body:JSON.stringify({email:$("authEmail").value.trim(),password:$("authPassword").value})});sessionStorage.setItem(SESSION_KEY,JSON.stringify(data));authStatus("Login सफल: "+data.account.email);status("Online account जुड़ गया।");await syncFeed();renderAll()}catch(e){authStatus("Login असफल: "+e.message)}});
$("registerAccount").addEventListener("click",async()=>{try{const data=await api("/v1/auth/register",{method:"POST",body:JSON.stringify({email:$("authEmail").value.trim(),password:$("authPassword").value,display_name:$("displayName").value.trim(),bio:$("bio").value.trim(),language:$("language").value})});sessionStorage.setItem(SESSION_KEY,JSON.stringify(data));authStatus("Account बनाया गया: "+data.account.email);status("नया online account तैयार है।");renderAll()}catch(e){authStatus("Registration असफल: "+e.message)}});
$("logoutAccount").addEventListener("click",()=>{sessionStorage.removeItem(SESSION_KEY);renderAll();status("Online account से logout हो गया।")});
renderAll();const initial=location.hash.slice(1);if(["home","create","learn","profile","data"].includes(initial))showTab(initial);
if(apiBase()&&session())syncFeed();
})();