#!/usr/bin/env python3
"""Archive oversized generated artifacts without losing their original bytes."""

from __future__ import annotations

import gzip
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GENERATED = ROOT / "generated"
THRESHOLD = 45 * 1024 * 1024
HARD_LIMIT = 95 * 1024 * 1024

TARGETS = [
    "verse-corpus.jsonl",
    "claim-evidence.jsonl",
    "formulation-records.jsonl",
    "reasoning-manifest.jsonl",
    "research-evidence-graph.json",
    "independent-verification-queue.jsonl",
    "independent-verification-registry.jsonl",
]


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def gzip_stream(src: Path, dst: Path) -> int:
    dst.parent.mkdir(parents=True, exist_ok=True)
    with src.open("rb") as inp, dst.open("wb") as raw:
        with gzip.GzipFile(fileobj=raw, mode="wb", mtime=0, filename="") as out:
            for chunk in iter(lambda: inp.read(1024 * 1024), b""):
                out.write(chunk)
    return dst.stat().st_size


def split_jsonl(path: Path):
    parts = []
    part_no = 1
    current = []
    current_bytes = 0
    with path.open("rb") as inp:
        for line in inp:
            if current and current_bytes + len(line) > THRESHOLD:
                raw = b"".join(current)
                part = path.with_name(f"{path.name}.part-{part_no:04d}.gz")
                with part.open("wb") as raw_out:
                    with gzip.GzipFile(fileobj=raw_out, mode="wb", mtime=0, filename="") as out:
                        out.write(raw)
                parts.append({"path": part.relative_to(ROOT).as_posix(), "stored_bytes": part.stat().st_size})
                part_no += 1
                current = []
                current_bytes = 0
            current.append(line)
            current_bytes += len(line)
    if current:
        raw = b"".join(current)
        part = path.with_name(f"{path.name}.part-{part_no:04d}.gz")
        with part.open("wb") as raw_out:
            with gzip.GzipFile(fileobj=raw_out, mode="wb", mtime=0, filename="") as out:
                out.write(raw)
        parts.append({"path": part.relative_to(ROOT).as_posix(), "stored_bytes": part.stat().st_size})
    return parts


def archive(path: Path) -> dict:
    original_size = path.stat().st_size
    original_hash = sha256(path)
    gz = path.with_suffix(path.suffix + ".gz")
    compressed_size = gzip_stream(path, gz)

    if compressed_size <= HARD_LIMIT:
        path.unlink()
        return {
            "source": path.relative_to(ROOT).as_posix(),
            "storage": [gz.relative_to(ROOT).as_posix()],
            "encoding": "gzip",
            "original_bytes": original_size,
            "stored_bytes": compressed_size,
            "original_sha256": original_hash,
        }

    gz.unlink(missing_ok=True)
    if path.suffix == ".jsonl":
        parts = split_jsonl(path)
        path.unlink()
        return {
            "source": path.relative_to(ROOT).as_posix(),
            "storage": [p["path"] for p in parts],
            "encoding": "gzip-jsonl-parts",
            "original_bytes": original_size,
            "stored_bytes": sum(p["stored_bytes"] for p in parts),
            "original_sha256": original_hash,
        }

    raise SystemExit(
        f"Cannot safely archive {path}: gzip output remains above {HARD_LIMIT} bytes."
    )


def main() -> None:
    records = []
    for name in TARGETS:
        path = GENERATED / name
        if path.exists() and path.stat().st_size > THRESHOLD:
            records.append(archive(path))

    manifest = {
        "version": 1,
        "policy": "Preserve generated bytes while keeping each GitHub-tracked file below the hard limit.",
        "threshold_bytes": THRESHOLD,
        "hard_limit_bytes": HARD_LIMIT,
        "artifacts": records,
    }
    (GENERATED / "LARGE-ARTIFACT-MANIFEST.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(manifest, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
