from pathlib import Path
import json,hashlib,html
from datetime import datetime,timezone
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/"generated"; MOD=ROOT/"products/modules"
F=[("calculator","Counting & Math"),("text","Text & Language"),("seo","SEO & Web"),("data","Data Tools"),("draw","Sketch & Drawing"),("pixel","Painting & Pixel Art"),("game","Mini Games"),("quiz","Education"),("research","Research"),("productivity","Productivity"),("media","Audio & Media"),("commerce","Commerce"),("access","Accessibility"),("visual","Visualization"),("quality","Security & Quality"),("ai","AI Prompt Tools"),("nlp","ML/NLP Tools"),("quantum","Quantum-Inspired"),("engineering","Engineering"),("knowledge","Knowledge"),("time","Calendar & Time"),("files","Files & Formats"),("marketing","Marketing"),("creator","Creator Tools"),("nature","Nature & Earth")]
def qc(pid): return "QC-"+hashlib.sha256((pid+"|SHIRMANI-QC").encode()).hexdigest()[:12].upper()
T='''<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SHIRMANI FAMILY Production Module</title><style>body{margin:0;background:#071018;color:#eef5f8;font:16px system-ui;line-height:1.5}main{max-width:1050px;margin:auto;padding:20px}.c{background:#101923;border:1px solid #354858;border-radius:16px;padding:18px;margin:12px 0}h1,h2{color:#ffd84a}input,textarea,select{width:100%;box-sizing:border-box;padding:10px;margin:5px 0 10px;background:#081019;color:#fff;border:1px solid #405466;border-radius:8px}button{padding:10px 14px;border:0;border-radius:8px;background:#ffd84a;font-weight:800}.tag{color:#5ee7ff}pre{white-space:pre-wrap;background:#060b10;padding:12px}#qr{background:#fff;padding:8px;display:inline-block}</style><script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script><main><section class=c><span class=tag>PRODUCTION MODULE • ENGINE</span><h1>꙰ SHIRMANI FAMILY</h1><p>Concrete executable browser module: <b id=pid></b></p><b>READY_FOR_QC</b></section><section class=c><h2>Product Passport</h2><p>QC: <b id=qc></b> · Gate: <b id=gate></b> · Dispatch: <b>NO</b></p><div id=qr></div><pre id=pass></pre></section><section class=c><h2>Working Module</h2><div id=tool></div><pre id=out>Ready.</pre></section><script>
const id=new URLSearchParams(location.search).get("id")||"UNASSIGNED",family="FAMILY",engine="ENGINE";function h(s){let x=2166136261;for(let c of s){x^=c.charCodeAt(0);x=Math.imul(x,16777619)}return(x>>>0).toString(16).toUpperCase().slice(0,12)}const qc="QC-"+h(id+"|SHIRMANI-QC"),gate="GATE-"+String(id.replace(/\D/g,"")||"0001").padStart(4,"0");function v(i){return document.getElementById(i)?.value||""}function o(x){out.textContent=JSON.stringify(x,null,2)}
pid.textContent=id;document.getElementById("qc").textContent=qc;document.getElementById("gate").textContent=gate;const passport={product_id:id,family,engine,qc_code:qc,gate_no:gate,dispatch_no:"NO",status:"READY_FOR_QC"};pass.textContent=JSON.stringify(passport,null,2);if(window.QRCode)new QRCode(qr,{text:location.href+"#"+JSON.stringify(passport),width:150,height:150});
const t=document.getElementById("tool");if(["calculator","engineering"].includes(engine))t.innerHTML='<input id=a type=number value=10><input id=b type=number value=5><select id=op><option>+</option><option>-</option><option>*</option><option>/</option></select><button onclick=calc()>Run</button>';else if(["text","nlp"].includes(engine))t.innerHTML='<textarea id=tx rows=7></textarea><button onclick=textx()>Analyze</button>';else if(["research","quality"].includes(engine))t.innerHTML='<input id=claim placeholder=Claim><input id=source placeholder=Source><textarea id=ev placeholder=Evidence></textarea><button onclick=research()>QC Record</button>';else if(["seo","marketing"].includes(engine))t.innerHTML='<input id=title placeholder=Title><textarea id=desc placeholder=Description></textarea><button onclick=seo()>SEO</button>';else if(["data","files"].includes(engine))t.innerHTML='<textarea id=data rows=8></textarea><button onclick=datax()>Inspect</button>';else if(engine=="game")t.innerHTML='<button onclick=game()>New Game</button><div id=board></div>';else if(["ai","creator","media","commerce"].includes(engine))t.innerHTML='<textarea id=brief rows=7 placeholder=Brief></textarea><button onclick=pack()>Package</button>';else t.innerHTML='<textarea id=note rows=7></textarea><button onclick=record()>Create</button>';
function calc(){let a=+v("a"),b=+v("b"),z=v("op");o({type:"CALCULATION",product_id:id,result:z=="+"?a+b:z=="-"?a-b:z=="*"?a*b:b?a/b:"DIV0",qc_code:qc})}function textx(){let x=v("tx");o({type:"TEXT_ANALYSIS",product_id:id,characters:x.length,words:x.trim()?x.trim().split(/\s+/).length:0})}function research(){o({type:"QC_EVIDENCE_RECORD",product_id:id,claim:v("claim"),source:v("source"),evidence:v("ev"),qc_code:qc,gate_no:gate,dispatch_no:"NO"})}function seo(){o({type:"SEO_PACK",product_id:id,title:v("title"),description:v("desc").slice(0,160)})}function datax(){let x=v("data");try{o({type:"JSON",product_id:id,value:JSON.parse(x)})}catch(e){o({type:"CSV",product_id:id,rows:x.split(/\n/).filter(Boolean).length})}}function pack(){o({type:"PRODUCTION_PACKAGE",product_id:id,brief:v("brief"),stages:["output","QC","dispatch"],qc_code:qc,gate_no:gate,dispatch_no:"NO"})}function record(){o({type:"STRUCTURED_RECORD",product_id:id,input:v("note"),status:"DRAFT"})}function game(){board.innerHTML=["","","","","","","","",""].map((_,i)=>'<button onclick="this.textContent=this.textContent?this.textContent:(i%2?"O":"X")" style="width:60px;height:60px;margin:3px"></button>').join("")}</script></main>'''
def main():
 OUT.mkdir(exist_ok=True);MOD.mkdir(parents=True,exist_ok=True)
 for e,f in F:(MOD/(e+".html")).write_text(T.replace("FAMILY",html.escape(f)).replace("ENGINE",e),encoding="utf-8")
 src=json.loads((OUT/"1000-digital-products.json").read_text())
 for p in src["products"]:
  e=p["engine"];m=f"products/modules/{e}.html";p.update(status="READY_FOR_QC",access=m+"?id="+p["id"],module=m,qc_code=qc(p["id"]),gate_no="GATE-"+p["id"].split("-")[1],dispatch_no="NO",verification="QC_GATE_PENDING")
 src["schema_version"]=2;src["principle"]="Each catalog product maps to a concrete browser production module; QC and dispatch are explicit gates."
 (OUT/"1000-digital-products.json").write_text(json.dumps(src,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
 with (OUT/"PRODUCT-PASSPORTS.jsonl").open("w",encoding="utf-8") as f:
  for p in src["products"]: f.write(json.dumps({"product_id":p["id"],"module":p["module"],"qc_code":p["qc_code"],"gate_no":p["gate_no"],"dispatch_no":"NO","status":"READY_FOR_QC","qr_payload":p["access"]+"|"+p["qc_code"]+"|"+p["gate_no"]+"|DISPATCH:NO"},ensure_ascii=False)+"\n")
 (OUT/"real-product-factory-status.json").write_text(json.dumps({"strategy":"CONCRETE_MODULE_PRODUCTION","target_products":1016,"catalog_products":len(src["products"]),"concrete_modules":len(F),"passports":"generated/PRODUCT-PASSPORTS.jsonl","verification_status":"QC_GATE_PENDING","dispatch_policy":"NO until explicit dispatch event"},indent=2)+"\n")
if __name__=="__main__":main()
