#!/usr/bin/env python3
import json
from pathlib import Path
from datetime import datetime, timezone
ROOT=Path(__file__).resolve().parents[1]; G=ROOT/"generated"
catalog=json.loads((G/"1000-digital-products.json").read_text(encoding="utf-8"))
products=catalog["products"]; ready=sum(p.get("status")=="READY_FOR_QC" for p in products)
offered=sum(p.get("commercial_status")=="CATALOG_READY" for p in products)
families=catalog["family_definitions"]
cards=[]
for p in products:
    cards.append(f'<article class="card"><span class="tag">{p["category"]}</span><h3>{p["name"]}</h3><p><b>{p["id"]}</b> · {p["engine"]}</p><p class="price">₹{p["offer_price_inr"]:,} <del>₹{p["price_inr"]:,}</del></p><p class="offer">{p["offer"]}</p><p>{p["description"]}</p><p>QC <b>{p["qc_code"]}</b> · Gate <b>{p["gate_no"]}</b> · Dispatch <b>{p["dispatch_no"]}</b></p><p>Guarantee: {p["guarantee"]} · {p["packing"]}</p><a href="{p["asset"]}">Open product</a> <a href="products/production-launch-center.html?id={p["id"]}">Showroom</a></article>')
html=f'''<!doctype html><html lang="hi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>꙰ SHIRMANI Supreme Production Dashboard</title><style>body{{margin:0;background:#061018;color:#eef5f8;font:16px system-ui;line-height:1.5}}main{{max-width:1400px;margin:auto;padding:22px 14px 80px}}h1,h2,h3{{color:#ffd84a}}.hero,.stat,.card{{background:#101923;border:1px solid #354858;border-radius:18px;padding:16px;margin:12px 0}}.hero{{border:2px solid #ffd84a}}.stats,.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}}.num{{font-size:2rem;font-weight:900}}.tag{{display:inline-block;border:1px solid #5ee7ff;border-radius:99px;padding:3px 9px;color:#5ee7ff;font-size:.75rem}}.price{{font-size:1.25rem;font-weight:900}}.offer{{font-weight:800}}a{{display:inline-block;background:#ffd84a;color:#101010;text-decoration:none;padding:9px 12px;border-radius:8px;font-weight:800}}del{{opacity:.6}}.muted{{opacity:.75}}input{{width:100%;box-sizing:border-box;padding:12px;background:#081019;color:#fff;border:1px solid #405466;border-radius:8px}}</style></head><body><main><section class="hero"><span class="tag">INSTITUTE → FACTORY → QC → SHOWROOM / SALE</span><h1>꙰ SHIRMANI Supreme Production Dashboard</h1><p>Production-first public control surface. Products are produced first; QC, gate and dispatch are downstream controls.</p><p class="muted">Updated {datetime.now(timezone.utc).isoformat()}</p><a href="products/production-launch-center.html">Enter Public Showroom</a></section><section class="stats"><div class="stat"><b>Product identities</b><div class="num">{len(products):,}</div></div><div class="stat"><b>Concrete product assets</b><div class="num">{ready:,}</div></div><div class="stat"><b>Catalog-ready / offered</b><div class="num">{offered:,}</div></div><div class="stat"><b>Dispatch YES</b><div class="num">0</div></div><div class="stat"><b>Categories / engines</b><div class="num">{len(families)}</div></div></section><section><h2>All product categories</h2><div class="grid">{"".join(f'<div class="card"><b>{x["label"]}</b><br>₹{x["base_price_inr"]:,} base</div>' for x in families)}</div></section><section><h2>Production catalogue</h2><input id="q" placeholder="Search product, category, engine…"><div id="grid" class="grid">{"".join(cards)}</div></section></main><script>const q=document.getElementById('q'),all=[...document.getElementById('grid').children];q.oninput=()=>{{const s=q.value.toLowerCase();all.forEach(x=>x.style.display=x.textContent.toLowerCase().includes(s)?'block':'none')}};</script></body></html>'''
(ROOT/"production-dashboard.html").write_text(html,encoding="utf-8")
