from pathlib import Path
import json,os,html
from datetime import datetime,timezone
ROOT=Path(__file__).resolve().parents[1]; CAT=ROOT/"generated/1000-digital-products.json"; OUT=ROOT/"products/live"; MAN=ROOT/"generated/product-surface-manifest.json"
def e(x): return html.escape(str(x or ""),quote=True)
def page(p):
 pid=str(p["id"]); name=p.get("name") or pid; fam=p.get("family") or p.get("category") or "Digital Product"; eng=p.get("engine") or "SHIRMANI"; desc=p.get("short_description") or p.get("description") or "Customer-facing digital product."; price=p.get("offer_price_inr",p.get("price_inr",""))
 return f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(name)} · SHIRMANI</title><style>body{{margin:0;background:#030812;color:#eef6ff;font-family:system-ui}}main{{max-width:1050px;margin:auto;padding:24px}}.card{{border:2px solid #e7c85b;border-radius:28px;padding:28px;background:linear-gradient(135deg,#07131d,#0a1c2d)}}h1{{color:#f6d35f;font-size:clamp(2rem,5vw,4rem)}}.tag{{color:#66ddff;font-weight:800}}a{{display:inline-block;padding:13px;margin:5px;border:1px solid #e7c85b;border-radius:12px;color:white;text-decoration:none}}.price{{color:#72e6aa;font-size:2rem;font-weight:900}}</style></head><body><main><section class="card"><div class="tag">SHIRMANI HEART-VIEW · PUBLIC PRODUCT</div><h1>{e(name)}</h1><p class="tag">{e(pid)} · {e(fam)} · {e(eng)}</p><p>{e(desc)}</p><p class="price">₹{e(price) if str(price) else "See offer"}</p><a href="../../product-passport.html?id={e(pid)}">📘 Passport / Long Description</a><a href="../../demos/vip/{e(pid.lower())}.svg">🖼️ VIP Screenshot</a><a href="../../demos/products/{e(pid.lower())}.mp4">🎬 Demo MP4</a><h2>How to use</h2><p>Open → enter task/input → run module → inspect result → reuse/export.</p><h2>Production state</h2><p>Public product surface, identity, description and offer slot. Sale, payment, delivery and independent verification are separate states.</p></section></main></body></html>"""
def main():
 data=json.loads(CAT.read_text(encoding="utf-8")); rows=[p for p in data.get("products",[]) if str(p.get("id","")).strip()]
 batch=max(1,min(100,int(os.getenv("PRODUCT_SURFACE_BATCH","25")))); OUT.mkdir(parents=True,exist_ok=True); existing={p.parent.name for p in OUT.glob("*/index.html")}; selected=[p for p in rows if str(p["id"]).lower() not in existing][:batch]
 for p in selected:
  d=OUT/str(p["id"]).lower(); d.mkdir(parents=True,exist_ok=True); (d/"index.html").write_text(page(p),encoding="utf-8")
 count=sum((OUT/str(p["id"]).lower()/"index.html").exists() for p in rows); payload={"schema_version":1,"generated_at":datetime.now(timezone.utc).isoformat(),"catalog_count":len(rows),"public_surface_count":count,"remaining_public_surfaces":len(rows)-count,"created_this_cycle":len(selected),"batch_size":batch,"state":"OPERATIONAL_SURFACE","truth_boundary":"Public surface is not evidence of sale, delivery, payment, scientific verification, or independent human review."}; MAN.write_text(json.dumps(payload,ensure_ascii=False,indent=2)+"\n",encoding="utf-8"); print(json.dumps(payload,ensure_ascii=False))
if __name__=="__main__": main()
