-- Compatibility notice.
-- Canonical public-platform PostgreSQL schema:
--   server/sql/schema.sql
-- 
-- Do not deploy this legacy reduced schema. It is retained only so older
-- tooling can detect the migration path. Production/deployment tooling must
-- apply server/sql/schema.sql and its migrations.
-- 
-- Truth boundary: applying a schema is not evidence that the API is LIVE,
-- AUTOMATED, or INDEPENDENTLY_VERIFIED.
