#!/usr/bin/env python3
from __future__ import annotations
import hashlib, html, json, os
from datetime import datetime, timezone
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
CATALOG=ROOT/"generated/1000-digital-products.json"
STATE=ROOT/"generated/production-state.json"
MANIFEST=ROOT/"generated/production-manifest.json"
BATCH=ROOT/"generated/production-batch.json"
OUT=ROOT/"generated/products"
BATCH_SIZE=int(os.getenv("PRODUCTION_BATCH_SIZE","50"))
LANES=["research","ai-ml-nlp","content","platform","economic","social-media","federation","security-quality","automation"]
PACKS={"Counting & Math":"interactive calculation and decision-support utility","Text & Language":"text transformation and language-analysis utility","SEO & Web":"web-content and SEO production utility","Data Tools":"structured data inspection and transformation utility","Research":"research workspace and evidence-record utility","Productivity":"task planning and productivity utility","AI Prompt Tools":"AI prompt and production-pack utility","ML/NLP Tools":"ML/NLP analysis and structured-output utility","Quantum-Inspired":"classical quantum-inspired workflow utility","Marketing":"marketing-content production utility","Nature & Earth":"nature/earth observation utility"}

def load(path, default):
    try: return json.loads(path.read_text(encoding="utf-8"))
    except Exception: return default

def code(prefix,pid): return prefix+"-"+hashlib.sha256(pid.encode()).hexdigest()[:10].upper()
def price(i): 
    base=89+(i*37)%4911
    return base,max(49,round(base*(0.70+((i*13)%21)/100)))

def make(p,lane,cycle):
    pid=p["id"]; i=int(pid.split("-")[-1]); base,offer=price(i); qc=code("QC",pid); gate=code("GATE",pid)
    family=p["family"]; desc=f"{p['name']} — {PACKS.get(family,'digital production utility')}. Concrete browser product artifact generated by the SHIRMANI production factory."
    payload={"product_id":pid,"name":p["name"],"family":family,"engine":p["engine"],"production_lane":lane,"production_cycle":cycle,"status":"PRODUCED_MVP","qc_code":qc,"gate_no":gate,"dispatch":"NO","price_inr":base,"offer_price_inr":offer,"guarantee":"30-day product-access/defect support policy; subject to final commercial terms","packing":"SUPREME_DIGITAL_PRIME","description":desc}
    s=html.escape
    page=f'''<!doctype html><html lang="hi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{s(p["name"])}</title><style>body{{font:16px system-ui;background:#071018;color:#eef5f8;max-width:1000px;margin:auto;padding:20px;line-height:1.6}}.hero,.card{{background:#101923;border:1px solid #354858;border-radius:18px;padding:18px;margin:12px 0}}h1,h2{{color:#ffd84a}}.tag{{border:1px solid #5ee7ff;border-radius:99px;padding:3px 8px;color:#5ee7ff}}.price{{font-size:1.6rem;color:#ffd84a;font-weight:900}}.ok{{color:#6ee7b7}}code{{color:#ffd84a}}</style></head><body><section class="hero"><span class="tag">PRODUCED • {s(family)} • {s(lane)}</span><h1>꙰ {s(p["name"])}</h1><p>{s(desc)}</p><p class="price">₹{offer:,} <del>₹{base:,}</del></p><p class="ok">Launch offer active in showroom catalogue.</p></section><section class="card"><h2>Product Passport</h2><p>Product ID: <code>{pid}</code></p><p>Engine: <code>{s(p["engine"])}</code></p><p>Production cycle: <code>{cycle}</code></p><p>QC Code: <code>{qc}</code></p><p>Gate No.: <code>{gate}</code></p><p>Dispatch: <b>NO</b></p><p>Packing: <code>SUPREME_DIGITAL_PRIME</code></p><p>Guarantee: 30-day product-access/defect support policy; subject to final commercial terms.</p></section><section class="card"><h2>QR Passport Payload</h2><code>{s(json.dumps(payload,separators=(",",":")))}</code><p class="ok">Production is recorded first; QC/gate/dispatch remain downstream controls.</p></section><p><a href="../../supreme-marking-hub.html">Supreme Marking Hub</a> · <a href="../../supreme-production-showroom.html">Showroom</a> · <a href="../../products/production-launch-center.html?id={pid}">Launch Center</a></p></body></html>'''
    return payload,page

def main():
    catalog=load(CATALOG,{}); products=catalog.get("products",[])
    if not products: raise SystemExit("catalog has no products")
    state=load(STATE,{"cursor":0,"cycle":0,"history":[]})
    cursor=int(state.get("cursor",0))%len(products); cycle=int(state.get("cycle",0))+1
    batch=products[cursor:cursor+BATCH_SIZE]
    if len(batch)<BATCH_SIZE: batch += products[:BATCH_SIZE-len(batch)]
    lane=LANES[(cycle-1)%len(LANES)]; OUT.mkdir(parents=True,exist_ok=True)
    made=[]
    for p in batch:
        payload,page=make(p,lane,cycle); (OUT/f"{p['id']}.html").write_text(page,encoding="utf-8"); made.append(payload)
    old=load(MANIFEST,{"products":[]}).get("products",[]); byid={x["product_id"]:x for x in old}
    for x in made: byid[x["product_id"]]=x
    produced=sorted(byid.values(),key=lambda x:x["product_id"]); remaining=max(0,len(products)-len(produced))
    now=datetime.now(timezone.utc).isoformat()
    newstate={"schema_version":1,"generated_at":now,"cursor":(cursor+len(batch))%len(products),"cycle":cycle,"batch_size":len(made),"lane":lane,"catalog_count":len(products),"produced_count":len(produced),"remaining_count":remaining,"history":(state.get("history",[])+[{"cycle":cycle,"lane":lane,"batch_size":len(made),"first":batch[0]["id"],"last":batch[-1]["id"]}])[-100:]}
    manifest={"schema_version":1,"generated_at":now,"production_cycle":cycle,"catalog_count":len(products),"produced_count":len(produced),"remaining_count":remaining,"lanes":LANES,"latest_batch":made,"products":produced}
    STATE.write_text(json.dumps(newstate,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    BATCH.write_text(json.dumps({"generated_at":now,"cycle":cycle,"lane":lane,"products":made},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    MANIFEST.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    print(json.dumps({"cycle":cycle,"lane":lane,"batch":len(made),"produced":len(produced),"remaining":remaining}))
if __name__=="__main__": main()
