#!/usr/bin/env python3
"""One concrete SHIRMANI digital product per scheduled cycle; stdlib only."""
import json, re
from datetime import datetime, timezone
from pathlib import Path

def load(path, fallback):
    try: return json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError): return fallback

def main():
    overlay_path=Path("generated/concrete-production-overlay.json")
    passport_path=Path("generated/PRODUCT-PASSPORTS.jsonl")
    state_path=Path("generated/live-production-state.json")
    visual_manifest_path=Path("products/visuals/manifest.json")
    overlay=load(overlay_path,{"schema_version":1,"architecture":["INSTITUTE","FACTORY","QC","SHOWROOM_SALE"],"products":[],"product_count":5000})
    products=overlay.setdefault("products",[])
    nums=[int(m.group(1)) for p in products if (m:=re.fullmatch(r"SP-(\d+)",str(p.get("id",""))))]
    n=max(nums or [0])+1
    if n>5000:
        print("5000 concrete product target reached; no duplicate generated.")
        return
    pid=f"SP-{n:04d}"
    families=[
      ("Yatharth Product Passport Builder","Product Operations","passport-builder","Build a structured digital product passport with description, pricing, guarantee, and production-state fields; export JSON."),
      ("Heart-View Review Insight Board","Customer Experience","review-insight","Capture customer feedback, summarize ratings, and turn comments into actionable quality-improvement notes."),
      ("Supreme Offer & Price Planner","Digital Commerce","offer-planner","Compare a regular price with an introductory offer and create a transparent offer card."),
      ("Yatharth Usage Guide Composer","Documentation","usage-guide","Create a practical usage guide with intended use, steps, limitations, and support notes.")
    ]
    title,family,engine,desc=families[(n-1)%len(families)]
    name=f"SHIRMANI {title} {n:04d}"
    now=datetime.now(timezone.utc).isoformat()
    artifact=f"products/concrete/{pid}.html"
    passport={"id":pid,"name":name,"category":family,"engine":engine,"module":artifact,"asset":artifact,
      "price_inr":199,"offer_price_inr":149,"offer":"INTRODUCTORY OFFER (catalogue metadata only)",
      "description":desc,"short_description":desc,"guarantee":"7-day digital quality correction window",
      "packing":"SUPREME DIGITAL PRIME PACK","qc_code":"QC-PENDING","gate_no":"GATE-PENDING","dispatch_no":"NO",
      "status":"PRODUCED_PENDING_QC","production_state":"PRODUCED_PENDING_QC","sale_state":"NOT_DISPATCHED",
      "produced_at":now,"qr_payload":f"{pid}|{artifact}|QC:QC-PENDING|GATE:GATE-PENDING|DISPATCH:NO|PRICE:149",
      "evidence_note":"Concrete artifact generated by scheduled production. QC, dispatch, sale and independent verification remain separate downstream states."}
    Path(artifact).parent.mkdir(parents=True,exist_ok=True)
    esc=lambda s: str(s).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace('"',"&quot;")
    html=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(name)}</title><style>body{{font:16px/1.6 system-ui;background:#07101a;color:#edf5ff;max-width:900px;margin:auto;padding:24px}}main{{border:1px solid #53677c;border-radius:18px;padding:24px;background:#0e1b29}}h1,h2{{color:#f0cf5a}}label{{display:block;margin-top:12px}}input,textarea{{width:100%;box-sizing:border-box;padding:10px;border-radius:8px;background:#06111c;color:white;border:1px solid #53677c}}button{{margin:10px 8px 0 0;padding:11px 16px;background:#f0cf5a;border:0;border-radius:8px;font-weight:800;cursor:pointer}}pre{{white-space:pre-wrap;overflow-wrap:anywhere;background:#06111c;padding:12px;border-radius:8px}}.tag{{color:#67e8f9}}</style><main><p class="tag">꙰ SHIRMANI · {pid} · CONCRETE DIGITAL TOOL</p><h1>{esc(name)}</h1><p>{esc(desc)}</p><p>Use the form to create a structured record, preview it, and export a JSON passport for your workflow.</p><label>Product name<input id="n" value="{esc(name)}"></label><label>Description<textarea id="d">{esc(desc)}</textarea></label><label>Regular price (INR)<input id="p" type="number" min="0" value="199"></label><label>Offer price (INR)<input id="o" type="number" min="0" value="149"></label><label>Guarantee<input id="g" value="7-day digital quality correction window"></label><button onclick="build()">Build passport</button><button onclick="download()">Export JSON</button><h2>Passport preview</h2><pre id="out"></pre><hr><p><b>Production:</b> PRODUCED_PENDING_QC · <b>QC:</b> QC-PENDING · <b>Gate:</b> GATE-PENDING · <b>Dispatch:</b> NO</p><p>Catalogue prices are not proof of a completed sale. This artifact does not claim QC clearance, dispatch, or independent verification.</p><a href="../../supreme-public-production-showroom.html">Public showroom</a></main><script>let data={{id:"{pid}",category:"{esc(family)}",engine:"{engine}",production_state:"PRODUCED_PENDING_QC",qc_code:"QC-PENDING",gate_no:"GATE-PENDING",dispatch_no:"NO"}};function build(){{data={{...data,name:document.querySelector("#n").value,description:document.querySelector("#d").value,price_inr:Number(document.querySelector("#p").value),offer_price_inr:Number(document.querySelector("#o").value),guarantee:document.querySelector("#g").value}};document.querySelector("#out").textContent=JSON.stringify(data,null,2)}}function download(){{build();let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{{type:"application/json"}}));a.download="{pid}-passport.json";a.click();URL.revokeObjectURL(a.href)}}build()</script></html>'''
    Path(artifact).write_text(html,encoding="utf-8")
    visual_dir=Path("products/visuals"); visual_dir.mkdir(parents=True,exist_ok=True)
    svg=f'''<svg xmlns="http://www.w3.org/2000/svg" width="3840" height="2160" viewBox="0 0 3840 2160"><defs><linearGradient id="bg"><stop stop-color="#07101a"/><stop offset="1" stop-color="#18354b"/></linearGradient></defs><rect width="3840" height="2160" fill="url(#bg)"/><rect x="80" y="80" width="3680" height="2000" rx="64" fill="none" stroke="#f0cf5a" stroke-width="8"/><text x="170" y="250" fill="#67e8f9" font-family="sans-serif" font-size="54">꙰ SHIRMANI · {pid}</text><text x="170" y="820" fill="#f0cf5a" font-family="sans-serif" font-weight="700" font-size="130">{esc(name)}</text><foreignObject x="170" y="930" width="3100" height="420"><div xmlns="http://www.w3.org/1999/xhtml" style="font:62px/1.35 sans-serif;color:#edf5ff">{esc(desc)}</div></foreignObject><text x="170" y="1830" fill="#67e8f9" font-family="sans-serif" font-size="48">Shiromani Rampal Saini · Impartial Understanding · Real · Natural Truth</text><text x="170" y="1940" fill="#f0cf5a" font-family="sans-serif" font-size="42">PRODUCTION ARTWORK · QC PENDING · DISPATCH NO</text></svg>'''
    (visual_dir/f"{pid.lower()}.svg").write_text(svg,encoding="utf-8")
    products.append({"id":pid,"name":name,"family":family,"engine":engine,"short_description":desc,
      "production_state":"PRODUCED_PENDING_QC","sale_state":"NOT_DISPATCHED","artifact_url":artifact,
      "production_batch":"AUTOMISSION-CYCLE","produced_at":now,"qc_code":"QC-PENDING","gate_no":"GATE-PENDING",
      "dispatch_no":"NO","price_inr":199,"offer_price_inr":149,"offer":"INTRODUCTORY OFFER"})
    overlay.update({"generated_at":now,"product_count":max(int(overlay.get("product_count",5000)),len(products)),
      "produced_count":len(products),"remaining_count":max(0,5000-len(products)),
      "last_cycle_product_id":pid,"last_cycle_concrete_results":1,"verification_is_downstream":True})
    overlay_path.write_text(json.dumps(overlay,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    lines=passport_path.read_text(encoding="utf-8").splitlines() if passport_path.exists() else []
    replaced=False
    for i,line in enumerate(lines):
        if line.strip() and json.loads(line).get("id")==pid:
            lines[i]=json.dumps(passport,ensure_ascii=False)
            replaced=True
            break
    if not replaced:
        lines.append(json.dumps(passport,ensure_ascii=False))
    passport_path.write_text("\\n".join(lines)+"\\n",encoding="utf-8")
    state=load(state_path,{})
    state.update({"generated_at":now,"catalog_identities":max(int(state.get("catalog_identities",5000)),len(products)),
      "concrete_repository_assets":len(products),"current_catalog_pending":max(0,5000-len(products)),
      "five_thousand_scale_target":5000,"remaining_to_scale_target":max(0,5000-len(products)),
      "concrete_materialization_percent_of_catalog":round(100*len(products)/5000,2),
      "concrete_materialization_percent_of_scale_target":round(100*len(products)/5000,2),
      "module_products_generated":len(products),"last_cycle_product_id":pid,"last_cycle_concrete_results":1,
      "dispatch_released":int(state.get("dispatch_released",0)),"sales_claimed":int(state.get("sales_claimed",0)),
      "payment_claimed":int(state.get("payment_claimed",0)),"independent_verification_claimed":int(state.get("independent_verification_claimed",0)),
      "state":"PRODUCTION_IN_PROGRESS"})
    state_path.write_text(json.dumps(state,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    vm=load(visual_manifest_path,{})
    vm.update({"generated_at":now,"format":"SVG 3840x2160 16:9 4K-ready","concrete_products":len(products),
      "total_visuals":len(list(visual_dir.glob("*.svg"))),"coverage_percent":round(100*len(list(visual_dir.glob("*.svg")))/max(1,len(products)),2),
      "last_cycle_product_id":pid,"principle":"Product visuals are presentation artifacts, not independent verification."})
    visual_manifest_path.write_text(json.dumps(vm,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    print(f"PRODUCED {pid}: {artifact}; 4K SVG created; QC pending; dispatch NO.")
if __name__=="__main__": main()
